/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTimetableRouteImport } from './routes/app.timetable'
import { Route as AppTeachersRouteImport } from './routes/app.teachers'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppFypRouteImport } from './routes/app.fyp'
import { Route as AppFeesRouteImport } from './routes/app.fees'
import { Route as AppDepartmentsRouteImport } from './routes/app.departments'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as AppComplaintsRouteImport } from './routes/app.complaints'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFypRoute = AppFypRouteImport.update({
  id: '/fyp',
  path: '/fyp',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/fyp': typeof AppFypRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/fyp': typeof AppFypRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/departments': typeof AppDepartmentsRoute
  '/app/fees': typeof AppFeesRoute
  '/app/fyp': typeof AppFypRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/teachers': typeof AppTeachersRoute
  '/app/timetable': typeof AppTimetableRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/complaints'
    | '/app/courses'
    | '/app/departments'
    | '/app/fees'
    | '/app/fyp'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/complaints'
    | '/app/courses'
    | '/app/departments'
    | '/app/fees'
    | '/app/fyp'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/attendance'
    | '/app/complaints'
    | '/app/courses'
    | '/app/departments'
    | '/app/fees'
    | '/app/fyp'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/timetable'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fyp': {
      id: '/app/fyp'
      path: '/fyp'
      fullPath: '/app/fyp'
      preLoaderRoute: typeof AppFypRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fees': {
      id: '/app/fees'
      path: '/fees'
      fullPath: '/app/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complaints': {
      id: '/app/complaints'
      path: '/complaints'
      fullPath: '/app/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppFeesRoute: typeof AppFeesRoute
  AppFypRoute: typeof AppFypRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppFeesRoute: AppFeesRoute,
  AppFypRoute: AppFypRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
